// <auto-generated />
using System;
using FarmControlAPI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FarmControlAPI.Infrastructure.Migrations
{
    [DbContext(typeof(FarmControlDbContext))]
    [Migration("20260915041315_AddPrecioUnitarioMovimientoInsumo")]
    partial class AddPrecioUnitarioMovimientoInsumo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Actividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParcelaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PersonaACargoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProcesoCultivoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoActividad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorDiaUsado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ParcelaId");

                    b.HasIndex("PersonaACargoId");

                    b.HasIndex("ProcesoCultivoId");

                    b.ToTable("Actividades");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.BitacoraEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorNombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ActorPersonaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BitacoraEntries");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.ClasificacionProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PesoUnidadKg")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnidadMedida")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("ClasificacionesProducto");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaVencimientoContrato")
                        .HasColumnType("TEXT");

                    b.Property<string>("NIT")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NIT")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdjuntoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("FincaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParcelaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProcesoCultivoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SocioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoCompra")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FincaId");

                    b.HasIndex("ParcelaId");

                    b.HasIndex("ProcesoCultivoId");

                    b.HasIndex("SocioId");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.DetalleVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Clasificacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("TEXT");

                    b.Property<int>("UnidadMedida")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VentaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VentaId");

                    b.ToTable("DetallesVenta");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Finca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AreaTotal")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CostoTerreno")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Fincas");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.HistorialPrecioVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Clasificacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnidadMedida")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VentaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VentaId");

                    b.ToTable("HistorialPreciosVenta");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Insumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Marca")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("StockMinimo")
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoInsumoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TipoInsumoId");

                    b.ToTable("Insumos");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.MovimientoInsumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("InsumoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParcelaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("PrecioUnitario")
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoMovimiento")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InsumoId");

                    b.HasIndex("ParcelaId");

                    b.ToTable("MovimientosInsumo");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Parcela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Area")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("FincaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FincaId");

                    b.HasIndex("ProductoId");

                    b.ToTable("Parcelas");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoPersona")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorDia")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.PersonaFinca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("FincaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonaId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoloLectura")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FincaId");

                    b.HasIndex("PersonaId", "FincaId")
                        .IsUnique();

                    b.ToTable("PersonasFincas");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.ProcesoCultivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CostoInicial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaEstimadaCosecha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParcelaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SocioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParcelaId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("SocioId");

                    b.ToTable("ProcesosCultivo");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.RegistroManoObra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActividadId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("HoraSalida")
                        .HasColumnType("TEXT");

                    b.Property<int>("JornaleroId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("NumHoras")
                        .HasColumnType("TEXT");

                    b.Property<int>("SocioId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorHora")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActividadId");

                    b.HasIndex("JornaleroId");

                    b.HasIndex("SocioId");

                    b.ToTable("RegistrosManoObra");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.TipoInsumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("TiposInsumo");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompradorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParcelaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProcesoCultivoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTransporte")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CompradorId");

                    b.HasIndex("ParcelaId");

                    b.HasIndex("ProcesoCultivoId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Actividad", b =>
                {
                    b.HasOne("FarmControlAPI.Domain.Entities.Parcela", "Parcela")
                        .WithMany("Actividades")
                        .HasForeignKey("ParcelaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmControlAPI.Domain.Entities.Persona", "PersonaACargo")
                        .WithMany("ActividadesACargo")
                        .HasForeignKey("PersonaACargoId");

                    b.HasOne("FarmControlAPI.Domain.Entities.ProcesoCultivo", "ProcesoCultivo")
                        .WithMany()
                        .HasForeignKey("ProcesoCultivoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Parcela");

                    b.Navigation("PersonaACargo");

                    b.Navigation("ProcesoCultivo");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.ClasificacionProducto", b =>
                {
                    b.HasOne("FarmControlAPI.Domain.Entities.Producto", "Producto")
                        .WithMany("Clasificaciones")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Compra", b =>
                {
                    b.HasOne("FarmControlAPI.Domain.Entities.Finca", "Finca")
                        .WithMany("Compras")
                        .HasForeignKey("FincaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmControlAPI.Domain.Entities.Parcela", "Parcela")
                        .WithMany()
                        .HasForeignKey("ParcelaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FarmControlAPI.Domain.Entities.ProcesoCultivo", "ProcesoCultivo")
                        .WithMany()
                        .HasForeignKey("ProcesoCultivoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FarmControlAPI.Domain.Entities.Persona", "Socio")
                        .WithMany("Compras")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Finca");

                    b.Navigation("Parcela");

                    b.Navigation("ProcesoCultivo");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.DetalleVenta", b =>
                {
                    b.HasOne("FarmControlAPI.Domain.Entities.Venta", "Venta")
                        .WithMany("Detalles")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Finca", b =>
                {
                    b.HasOne("FarmControlAPI.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Fincas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.HistorialPrecioVenta", b =>
                {
                    b.HasOne("FarmControlAPI.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FarmControlAPI.Domain.Entities.Venta", "Venta")
                        .WithMany()
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Insumo", b =>
                {
                    b.HasOne("FarmControlAPI.Domain.Entities.TipoInsumo", "TipoInsumo")
                        .WithMany("Insumos")
                        .HasForeignKey("TipoInsumoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoInsumo");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.MovimientoInsumo", b =>
                {
                    b.HasOne("FarmControlAPI.Domain.Entities.Insumo", "Insumo")
                        .WithMany("Movimientos")
                        .HasForeignKey("InsumoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmControlAPI.Domain.Entities.Parcela", "Parcela")
                        .WithMany("MovimientosInsumo")
                        .HasForeignKey("ParcelaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insumo");

                    b.Navigation("Parcela");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Parcela", b =>
                {
                    b.HasOne("FarmControlAPI.Domain.Entities.Finca", "Finca")
                        .WithMany("Parcelas")
                        .HasForeignKey("FincaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmControlAPI.Domain.Entities.Producto", null)
                        .WithMany("Parcelas")
                        .HasForeignKey("ProductoId");

                    b.Navigation("Finca");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Persona", b =>
                {
                    b.HasOne("FarmControlAPI.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.PersonaFinca", b =>
                {
                    b.HasOne("FarmControlAPI.Domain.Entities.Finca", "Finca")
                        .WithMany("AsignacionesPersona")
                        .HasForeignKey("FincaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmControlAPI.Domain.Entities.Persona", "Persona")
                        .WithMany("AsignacionesFinca")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Finca");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.ProcesoCultivo", b =>
                {
                    b.HasOne("FarmControlAPI.Domain.Entities.Parcela", "Parcela")
                        .WithMany("ProcesosCultivo")
                        .HasForeignKey("ParcelaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmControlAPI.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FarmControlAPI.Domain.Entities.Persona", "Socio")
                        .WithMany()
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Parcela");

                    b.Navigation("Producto");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Producto", b =>
                {
                    b.HasOne("FarmControlAPI.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Productos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.RegistroManoObra", b =>
                {
                    b.HasOne("FarmControlAPI.Domain.Entities.Actividad", "Actividad")
                        .WithMany("RegistrosManoObra")
                        .HasForeignKey("ActividadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmControlAPI.Domain.Entities.Persona", "Jornalero")
                        .WithMany("RegistrosComoJornalero")
                        .HasForeignKey("JornaleroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FarmControlAPI.Domain.Entities.Persona", "Socio")
                        .WithMany("RegistrosComoPagador")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Actividad");

                    b.Navigation("Jornalero");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.TipoInsumo", b =>
                {
                    b.HasOne("FarmControlAPI.Domain.Entities.Cliente", "Cliente")
                        .WithMany("TiposInsumo")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Venta", b =>
                {
                    b.HasOne("FarmControlAPI.Domain.Entities.Persona", "Comprador")
                        .WithMany("Ventas")
                        .HasForeignKey("CompradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FarmControlAPI.Domain.Entities.Parcela", "Parcela")
                        .WithMany("Ventas")
                        .HasForeignKey("ParcelaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmControlAPI.Domain.Entities.ProcesoCultivo", "ProcesoCultivo")
                        .WithMany()
                        .HasForeignKey("ProcesoCultivoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Comprador");

                    b.Navigation("Parcela");

                    b.Navigation("ProcesoCultivo");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Actividad", b =>
                {
                    b.Navigation("RegistrosManoObra");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Fincas");

                    b.Navigation("Productos");

                    b.Navigation("TiposInsumo");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Finca", b =>
                {
                    b.Navigation("AsignacionesPersona");

                    b.Navigation("Compras");

                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Insumo", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Parcela", b =>
                {
                    b.Navigation("Actividades");

                    b.Navigation("MovimientosInsumo");

                    b.Navigation("ProcesosCultivo");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Persona", b =>
                {
                    b.Navigation("ActividadesACargo");

                    b.Navigation("AsignacionesFinca");

                    b.Navigation("Compras");

                    b.Navigation("RegistrosComoJornalero");

                    b.Navigation("RegistrosComoPagador");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Producto", b =>
                {
                    b.Navigation("Clasificaciones");

                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.TipoInsumo", b =>
                {
                    b.Navigation("Insumos");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Venta", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
