// <auto-generated />
using System;
using FarmControlAPI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FarmControlAPI.Infrastructure.Migrations
{
    [DbContext(typeof(FarmControlDbContext))]
    partial class FarmControlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Actividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Confirmada")
                        .HasColumnType("boolean");

                    b.Property<string>("ConfirmadaPor")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaConfirmacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ParcelaId")
                        .HasColumnType("integer");

                    b.Property<int?>("PersonaACargoId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProcesoCultivoId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoActividad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValorDiaUsado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ParcelaId");

                    b.HasIndex("PersonaACargoId");

                    b.HasIndex("ProcesoCultivoId");

                    b.ToTable("Actividades");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.AnalisisSuelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Fosforo")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MateriaOrganica")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Nitrogeno")
                        .HasColumnType("numeric");

                    b.Property<string>("Observacion")
                        .HasColumnType("text");

                    b.Property<int>("ParcelaId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Ph")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Potasio")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ParcelaId");

                    b.ToTable("AnalisisSuelo");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Asistencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FincaId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("HoraEntrada")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("HoraSalida")
                        .HasColumnType("interval");

                    b.Property<string>("Observacion")
                        .HasColumnType("text");

                    b.Property<int>("PersonaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FincaId");

                    b.HasIndex("PersonaId");

                    b.ToTable("Asistencias");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.BitacoraEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActorNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ActorPersonaId")
                        .HasColumnType("integer");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("BitacoraEntries");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.ClasificacionProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PesoUnidadKg")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<int>("UnidadMedida")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("ClasificacionesProducto");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaVencimientoContrato")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NIT")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PlanId")
                        .HasColumnType("integer");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NIT")
                        .IsUnique();

                    b.HasIndex("PlanId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorPersonaId")
                        .HasColumnType("integer");

                    b.Property<int>("EntidadId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipoEntidad")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AutorPersonaId");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdjuntoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FincaId")
                        .HasColumnType("integer");

                    b.Property<int?>("ParcelaId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProcesoCultivoId")
                        .HasColumnType("integer");

                    b.Property<string>("Proveedor")
                        .HasColumnType("text");

                    b.Property<int>("SocioId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoCompra")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FincaId");

                    b.HasIndex("ParcelaId");

                    b.HasIndex("ProcesoCultivoId");

                    b.HasIndex("SocioId");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.DetalleVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric");

                    b.Property<string>("Clasificacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric");

                    b.Property<int>("UnidadMedida")
                        .HasColumnType("integer");

                    b.Property<int>("VentaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VentaId");

                    b.ToTable("DetallesVenta");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Finca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AreaTotal")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<decimal>("CostoTerreno")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Fincas");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.HistorialPrecioVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Clasificacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<int>("UnidadMedida")
                        .HasColumnType("integer");

                    b.Property<int>("VentaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VentaId");

                    b.ToTable("HistorialPreciosVenta");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Insumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Marca")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("StockMinimo")
                        .HasColumnType("numeric");

                    b.Property<int>("TipoInsumoId")
                        .HasColumnType("integer");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TipoInsumoId");

                    b.ToTable("Insumos");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.LiquidacionNomina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaLiquidacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("JornaleroId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacion")
                        .HasColumnType("text");

                    b.Property<decimal>("TotalHoras")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalPagar")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("JornaleroId");

                    b.ToTable("LiquidacionesNomina");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.MovimientoInsumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InsumoId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacion")
                        .HasColumnType("text");

                    b.Property<int>("ParcelaId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PrecioUnitario")
                        .HasColumnType("numeric");

                    b.Property<int>("TipoMovimiento")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InsumoId");

                    b.HasIndex("ParcelaId");

                    b.ToTable("MovimientosInsumo");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.PagoCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompraId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.Property<string>("Observacion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompraId");

                    b.ToTable("PagosCompra");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.PagoVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.Property<string>("Observacion")
                        .HasColumnType("text");

                    b.Property<int>("VentaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VentaId");

                    b.ToTable("PagosVenta");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Parcela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Area")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("FincaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FincaId");

                    b.HasIndex("ProductoId");

                    b.ToTable("Parcelas");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PreferenciasDashboardJson")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipoPersona")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorDia")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.PersonaFinca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FincaId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonaId")
                        .HasColumnType("integer");

                    b.Property<bool>("PuedeEliminar")
                        .HasColumnType("boolean");

                    b.Property<bool>("SoloLectura")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("FincaId");

                    b.HasIndex("PersonaId", "FincaId")
                        .IsUnique();

                    b.ToTable("PersonasFincas");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<int>("MaxFincas")
                        .HasColumnType("integer");

                    b.Property<int>("MaxUsuarios")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Planes");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.ProcesoCultivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostoInicial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaEstimadaCosecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ParcelaId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<int?>("SocioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParcelaId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("SocioId");

                    b.ToTable("ProcesosCultivo");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.RegistroManoObra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActividadId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraSalida")
                        .HasColumnType("interval");

                    b.Property<int>("JornaleroId")
                        .HasColumnType("integer");

                    b.Property<int?>("LiquidacionNominaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("NumHoras")
                        .HasColumnType("numeric");

                    b.Property<int>("SocioId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorHora")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ActividadId");

                    b.HasIndex("JornaleroId");

                    b.HasIndex("LiquidacionNominaId");

                    b.HasIndex("SocioId");

                    b.ToTable("RegistrosManoObra");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.ReporteCompartido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreadoPorPersonaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaExpiracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FincaId")
                        .HasColumnType("integer");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FincaId");

                    b.ToTable("ReportesCompartidos");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.TareaRecurrente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FrecuenciaDias")
                        .HasColumnType("integer");

                    b.Property<int>("ParcelaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ProximaFecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UltimaEjecucion")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParcelaId");

                    b.ToTable("TareasRecurrentes");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.TipoInsumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("TiposInsumo");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompradorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ParcelaId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProcesoCultivoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTransporte")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CompradorId");

                    b.HasIndex("ParcelaId");

                    b.HasIndex("ProcesoCultivoId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Actividad", b =>
                {
                    b.HasOne("FarmControlAPI.Domain.Entities.Parcela", "Parcela")
                        .WithMany("Actividades")
                        .HasForeignKey("ParcelaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmControlAPI.Domain.Entities.Persona", "PersonaACargo")
                        .WithMany("ActividadesACargo")
                        .HasForeignKey("PersonaACargoId");

                    b.HasOne("FarmControlAPI.Domain.Entities.ProcesoCultivo", "ProcesoCultivo")
                        .WithMany()
                        .HasForeignKey("ProcesoCultivoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Parcela");

                    b.Navigation("PersonaACargo");

                    b.Navigation("ProcesoCultivo");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.AnalisisSuelo", b =>
                {
                    b.HasOne("FarmControlAPI.Domain.Entities.Parcela", "Parcela")
                        .WithMany("AnalisisSuelo")
                        .HasForeignKey("ParcelaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parcela");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Asistencia", b =>
                {
                    b.HasOne("FarmControlAPI.Domain.Entities.Finca", "Finca")
                        .WithMany()
                        .HasForeignKey("FincaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmControlAPI.Domain.Entities.Persona", "Persona")
                        .WithMany("Asistencias")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Finca");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.ClasificacionProducto", b =>
                {
                    b.HasOne("FarmControlAPI.Domain.Entities.Producto", "Producto")
                        .WithMany("Clasificaciones")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("FarmControlAPI.Domain.Entities.Plan", "Plan")
                        .WithMany("Clientes")
                        .HasForeignKey("PlanId");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Comentario", b =>
                {
                    b.HasOne("FarmControlAPI.Domain.Entities.Persona", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorPersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Compra", b =>
                {
                    b.HasOne("FarmControlAPI.Domain.Entities.Finca", "Finca")
                        .WithMany("Compras")
                        .HasForeignKey("FincaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmControlAPI.Domain.Entities.Parcela", "Parcela")
                        .WithMany()
                        .HasForeignKey("ParcelaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FarmControlAPI.Domain.Entities.ProcesoCultivo", "ProcesoCultivo")
                        .WithMany()
                        .HasForeignKey("ProcesoCultivoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FarmControlAPI.Domain.Entities.Persona", "Socio")
                        .WithMany("Compras")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Finca");

                    b.Navigation("Parcela");

                    b.Navigation("ProcesoCultivo");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.DetalleVenta", b =>
                {
                    b.HasOne("FarmControlAPI.Domain.Entities.Venta", "Venta")
                        .WithMany("Detalles")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Finca", b =>
                {
                    b.HasOne("FarmControlAPI.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Fincas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.HistorialPrecioVenta", b =>
                {
                    b.HasOne("FarmControlAPI.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FarmControlAPI.Domain.Entities.Venta", "Venta")
                        .WithMany()
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Insumo", b =>
                {
                    b.HasOne("FarmControlAPI.Domain.Entities.TipoInsumo", "TipoInsumo")
                        .WithMany("Insumos")
                        .HasForeignKey("TipoInsumoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoInsumo");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.LiquidacionNomina", b =>
                {
                    b.HasOne("FarmControlAPI.Domain.Entities.Persona", "Jornalero")
                        .WithMany("Liquidaciones")
                        .HasForeignKey("JornaleroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jornalero");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.MovimientoInsumo", b =>
                {
                    b.HasOne("FarmControlAPI.Domain.Entities.Insumo", "Insumo")
                        .WithMany("Movimientos")
                        .HasForeignKey("InsumoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmControlAPI.Domain.Entities.Parcela", "Parcela")
                        .WithMany("MovimientosInsumo")
                        .HasForeignKey("ParcelaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insumo");

                    b.Navigation("Parcela");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.PagoCompra", b =>
                {
                    b.HasOne("FarmControlAPI.Domain.Entities.Compra", "Compra")
                        .WithMany("Pagos")
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compra");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.PagoVenta", b =>
                {
                    b.HasOne("FarmControlAPI.Domain.Entities.Venta", "Venta")
                        .WithMany("Pagos")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Parcela", b =>
                {
                    b.HasOne("FarmControlAPI.Domain.Entities.Finca", "Finca")
                        .WithMany("Parcelas")
                        .HasForeignKey("FincaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmControlAPI.Domain.Entities.Producto", null)
                        .WithMany("Parcelas")
                        .HasForeignKey("ProductoId");

                    b.Navigation("Finca");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Persona", b =>
                {
                    b.HasOne("FarmControlAPI.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.PersonaFinca", b =>
                {
                    b.HasOne("FarmControlAPI.Domain.Entities.Finca", "Finca")
                        .WithMany("AsignacionesPersona")
                        .HasForeignKey("FincaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmControlAPI.Domain.Entities.Persona", "Persona")
                        .WithMany("AsignacionesFinca")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Finca");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.ProcesoCultivo", b =>
                {
                    b.HasOne("FarmControlAPI.Domain.Entities.Parcela", "Parcela")
                        .WithMany("ProcesosCultivo")
                        .HasForeignKey("ParcelaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmControlAPI.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FarmControlAPI.Domain.Entities.Persona", "Socio")
                        .WithMany()
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Parcela");

                    b.Navigation("Producto");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Producto", b =>
                {
                    b.HasOne("FarmControlAPI.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Productos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.RegistroManoObra", b =>
                {
                    b.HasOne("FarmControlAPI.Domain.Entities.Actividad", "Actividad")
                        .WithMany("RegistrosManoObra")
                        .HasForeignKey("ActividadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmControlAPI.Domain.Entities.Persona", "Jornalero")
                        .WithMany("RegistrosComoJornalero")
                        .HasForeignKey("JornaleroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FarmControlAPI.Domain.Entities.LiquidacionNomina", "LiquidacionNomina")
                        .WithMany("Registros")
                        .HasForeignKey("LiquidacionNominaId");

                    b.HasOne("FarmControlAPI.Domain.Entities.Persona", "Socio")
                        .WithMany("RegistrosComoPagador")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Actividad");

                    b.Navigation("Jornalero");

                    b.Navigation("LiquidacionNomina");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.ReporteCompartido", b =>
                {
                    b.HasOne("FarmControlAPI.Domain.Entities.Finca", "Finca")
                        .WithMany()
                        .HasForeignKey("FincaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Finca");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.TareaRecurrente", b =>
                {
                    b.HasOne("FarmControlAPI.Domain.Entities.Parcela", "Parcela")
                        .WithMany("TareasRecurrentes")
                        .HasForeignKey("ParcelaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parcela");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.TipoInsumo", b =>
                {
                    b.HasOne("FarmControlAPI.Domain.Entities.Cliente", "Cliente")
                        .WithMany("TiposInsumo")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Venta", b =>
                {
                    b.HasOne("FarmControlAPI.Domain.Entities.Persona", "Comprador")
                        .WithMany("Ventas")
                        .HasForeignKey("CompradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FarmControlAPI.Domain.Entities.Parcela", "Parcela")
                        .WithMany("Ventas")
                        .HasForeignKey("ParcelaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmControlAPI.Domain.Entities.ProcesoCultivo", "ProcesoCultivo")
                        .WithMany()
                        .HasForeignKey("ProcesoCultivoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Comprador");

                    b.Navigation("Parcela");

                    b.Navigation("ProcesoCultivo");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Actividad", b =>
                {
                    b.Navigation("RegistrosManoObra");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Fincas");

                    b.Navigation("Productos");

                    b.Navigation("TiposInsumo");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Compra", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Finca", b =>
                {
                    b.Navigation("AsignacionesPersona");

                    b.Navigation("Compras");

                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Insumo", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.LiquidacionNomina", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Parcela", b =>
                {
                    b.Navigation("Actividades");

                    b.Navigation("AnalisisSuelo");

                    b.Navigation("MovimientosInsumo");

                    b.Navigation("ProcesosCultivo");

                    b.Navigation("TareasRecurrentes");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Persona", b =>
                {
                    b.Navigation("ActividadesACargo");

                    b.Navigation("AsignacionesFinca");

                    b.Navigation("Asistencias");

                    b.Navigation("Compras");

                    b.Navigation("Liquidaciones");

                    b.Navigation("RegistrosComoJornalero");

                    b.Navigation("RegistrosComoPagador");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Plan", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Producto", b =>
                {
                    b.Navigation("Clasificaciones");

                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.TipoInsumo", b =>
                {
                    b.Navigation("Insumos");
                });

            modelBuilder.Entity("FarmControlAPI.Domain.Entities.Venta", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Pagos");
                });
#pragma warning restore 612, 618
        }
    }
}
